### ISSUE TITLE
Provide a ES5 version

### ISSUE THREAD

**Issue by KennyWho** [zeit/swr#163]
In `tsconfig.js`, the `target` is `esnext`, but in real world, we need support some device in iOS 9, so we perhaps need a ES5 version.

**Comment by quietshu** [comment]
Should be fixed in v0.1.14.

**Comment by nghiepit** [comment]
@quietshu In v0.1.15, I still see the syntax es6 in sources code build.

![image](https://user-images.githubusercontent.com/4768095/71306420-71792f00-2412-11ea-9775-a4faf1929282.png)
